baseURL: "https://tai-bennett.github.io" 
title: Duncan Tai Bennett
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Porfolio
          url: portfolio/
          weight: 1
        # - name: Talks
        #   url: talks/
        #   weight: 2
        - name: About
          url: about/
          weight: 3 
        - name: Resume
          url: dtb-resume.pdf
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a postdoctoral researcher in quantum algorithms at ENSTA - Institut Polytechnique de Paris."
    author: Duncan Tai Bennett
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "02 Jan 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Duncan Tai Bennett
          subtitle: "I am a postdoctoral researcher at the applied mathematics department of ENSTA from the Institut Polytechnique de Paris. I am also affiliated with the combinatorial optimization team in the CEDRIC lab at the Conservatoire National des Arts et Métiers. I work with Andrea Simonetto, and Sourour Elloumi. My research focuses on quantum algorithms for optimization problems, algebraic combinatorics and cooperative game theory.<br><br>In September 2026, I will join the LIP6 at Sorbonne Université as an assistant professor, in the Décision team."
          imageUrl: "headshot.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Duncan Tai Bennett
          buttons:
            - name: Portfolio
              url: portfolio/
            # - name: Talks
            #   url: talks/
            - name: About
              url: about/
            - name: Resume
              url: dtb-resume.pdf
            # - name: Archive
            #   url: archive/
    socialIcons:
        # - name: hal
        #   url: https://cv.hal.science/dylan-laplace-mermoud
        # - name: arXiv
        #   url: http://arxiv.org/a/laplacemermoud_d_1
        - name: substack
          url: https://substack/@backpropagatingpear
        # - name: CV
        #   url: cv.pdf
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/tai-bennett
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat
        - name: Email
          url: mailto:bennettduncantai@gmail.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
        favicon: "/favicon.ico"
        favicon16x16: "/favicon-16x16.png"
        favicon32x32: "/favicon-32x32.png"
        apple_touch_icon: "/apple-touch-icon.png"
        mask_icon: "/safari-pinned-tab.svg"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Duncan Tai Bennett"
      icon: pear.jpg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
