baseURL: "https://tai-bennett.github.io" 
title: Duncan Tai Bennett
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Porfolio
          url: portfolio/
          weight: 1
        # - name: Talks
        #   url: talks/
        #   weight: 2
        - name: About
          url: about/
          weight: 3 
        - name: Resume
          url: dtb-resume.pdf
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a Mathematics PhD from the University of Arizona specializing in dynamical systems and machine learning. My research analyzes machine learning models as dynamical systems and interprets the dynamical properties in the ML setting. My dissertation is titled Computer-Assisted Proofs of Chaos in the Long Short-Term Memory Model and I was advised by Dr. Marek Rychlik."
    author: Duncan Tai Bennett
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "02 Jan 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Duncan Tai Bennett
          subtitle: "I am a Mathematics PhD from the University of Arizona specializing in dynamical systems and machine learning. My research analyzes machine learning models as dynamical systems and interprets the dynamical properties in the ML setting. My dissertation is titled Computer-Assisted Proofs of Chaos in the Long Short-Term Memory Model and I was advised by Dr. Marek Rychlik."
          imageUrl: "headshot.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Duncan Tai Bennett
          buttons:
            - name: Portfolio
              url: portfolio/
            # - name: Talks
            #   url: talks/
            - name: About
              url: about/
            - name: Resume
              url: dtb-resume.pdf
            # - name: Archive
            #   url: archive/
    socialIcons:
        # - name: hal
        #   url: https://cv.hal.science/dylan-laplace-mermoud
        # - name: arXiv
        #   url: http://arxiv.org/a/laplacemermoud_d_1
        - name: substack
          url: https://substack/@backpropagatingpear
        - name: linkedin
          url: https://linkedin/in/bennettduncantai
        # - name: CV
        #   url: cv.pdf
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: YouTube
        #   url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/tai-bennett
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: Twitter
        #   url: https://twitter.com/pmichaillat
        - name: Email
          url: mailto:bennettduncantai@gmail.com

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
        favicon: "/pear.jpg" 
        favicon16x16: "/pear.jpg"
        favicon32x32: "/pear.jpg"
        apple_touch_icon: "/pear.jpg"
        mask_icon: "/pear.jpg"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Duncan Tai Bennett"
      icon: pear.jpg
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
